services:
  # Service 1: Rust Backend
  backend:
    build: ./task-server # Look for the Dockerfile in this folder
    ports:
      - "3000:3000" # Open port 3000
    restart: always # On crashing restart automatically
    volumes:
      - ./task-server/tasks.db:/tasks.db # real file : fake file

  # Service 2: The React Frontend
  frontend:
    build: ./task-manager # Look for the Dockerfile in this folder
    ports:
      - "8080:80" # Map laptop port 8080 -> container port 80
    restart: always
    depends_on:
      - backend # Wait for backend to start first
